// frontend/src/features/jobs/jobMocks.ts
import type {JobPosting, JobMatchingRunDetail} from "@/lib/contracts";

export const mockJobPosting: JobPosting = {
  id: "dummy-job-id",
  tenantId: "mock-tenant",
  title: "Senior React Developer",
  employerName: "Tech Corp",
  employerCountry: "UAE",
  employerRegion: "GCC",
  jobDescription: "We are looking for a Senior React Developer to join our team in Dubai. The ideal candidate will have experience with React, TypeScript, and REST APIs. You will be responsible for building and maintaining high-quality web applications. Responsibilities include developing new user-facing features, optimizing components for maximum performance, and collaborating with the design team to implement pixel-perfect UIs.",
  requiredSkills: ["React", "TypeScript", "REST APIs"],
  preferredSkills: ["Next.js", "GraphQL"],
  seniorityLevel: "Senior",
  employmentType: "Full-time",
  postedDate: new Date().toISOString(),
  applicationDeadline: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
  status: "active",
  locationInfo: {
    country: "UAE",
    city: "Dubai",
    region: "GCC",
    remotePolicy: "Hybrid",
  },
  keyResponsibilities: ["Develop new user-facing features", "Optimize components", "Collaborate with design team"],
  aiProfile: {},
  aiConfidence: {},
  createdByUserId: null,
  updatedByUserId: null,
  closedAt: null,
  closedByUserId: null,
  isPublic: true,
  publicSlug: "senior-react-developer-dubai",
  publicTitle: "Senior React Developer",
  publicSummary: "Join Tech Corp in Dubai as a Senior React Developer.",
  publicDescription: "Redacted public description for Senior React Developer role.",
  publicLocation: "Dubai, UAE",
  publicApplyEnabled: true,
  publicPublishedAt: new Date().toISOString(),
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
};

export const mockMatchingRunDetail: JobMatchingRunDetail = {
  run: {
    id: "dummy-run-id",
    tenantId: "mock-tenant",
    jobPostingId: "dummy-job-id",
    initiatedByUserId: null,
    status: "completed",
    requestedLimit: 20,
    semanticPoolSize: 200,
    rerankPoolSize: 50,
    retrievedCount: 50,
    filteredCount: 30,
    rerankedCount: 20,
    completedCount: 1,
    failureReason: null,
    matchingConfig: {},
    jobProfile: {},
    embeddingProvider: null,
    embeddingVersion: null,
    startedAt: new Date().toISOString(),
    completedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  results: [
    {
      id: "match-1",
      tenantId: "mock-tenant",
      matchingRunId: "dummy-run-id",
      jobPostingId: "dummy-job-id",
      candidateId: "candidate-1",
      sourceTenantId: null,
      rank: 1,
      semanticScore: 0.9,
      aiScore: 0.85,
      finalScore: 0.88,
      matchedSkills: ["React", "TypeScript"],
      missingSkills: ["GraphQL"],
      seniorityAlignment: "Exact Match",
      experienceSummary: "8 years of experience in frontend development with React.",
      matchExplanation: "Strong match based on React and TypeScript skills. Missing GraphQL which is a preferred skill.",
      scoringBreakdown: {},
      hardFilterPayload: {},
      candidateSnapshot: { name: "Jane Doe", current_title: "Senior Frontend Engineer", location: "Dubai, UAE" },
      createdAt: new Date().toISOString(),
    },
  ],
};
