from __future__ import annotations

import re


SKILL_ALIASES = {
    ".net-4": ".NET",
    ".net-4-0": ".NET",
    ".net-4-8": ".NET",
    ".net-5": ".NET",
    ".net-6": ".NET",
    ".net-7": ".NET",
    ".net-8": ".NET",
    ".net-core": ".NET",
    ".net-api": ".NET",
    ".net-ecosystem": ".NET",
    ".net-framework": ".NET",
    ".net-maui": ".NET MAUI",
    ".net-playwright": ".NET",
    ".net-zero-framework": ".NET",
    "abp-.net-framework": "ABP Framework",
    "ado-.net": "ADO.NET",
    "ado.net": "ADO.NET",
    "angularjs": "Angular",
    "api": "APIs",
    "apis": "APIs",
    "asp-net": "ASP.NET",
    "asp-net-api": "ASP.NET",
    "asp-net-core": "ASP.NET Core",
    "asp-net-core-api": "ASP.NET Core",
    "asp-net-core-c": "ASP.NET Core",
    "asp-net-core-identity": "ASP.NET Core",
    "asp-net-core-mvc": "ASP.NET Core",
    "asp-net-core-web-api": "ASP.NET Core",
    "asp-net-core-webapi": "ASP.NET Core",
    "asp-net-framework": "ASP.NET",
    "asp-net-mvc": "ASP.NET MVC",
    "asp-net-web-api": "ASP.NET",
    "asp-net-web-api2": "ASP.NET",
    "asp-net-web-forms": "ASP.NET",
    "aspnet-boilerplate": "ABP Framework",
    "aws": "AWS",
    "azure": "Azure",
    "azure-devops": "Azure DevOps",
    "bloc": "Bloc",
    "bloc-cubit": "Bloc/Cubit",
    "blazor.net": "Blazor",
    "blazor-net": "Blazor",
    "c#": "C#",
    "c-sharp": "C#",
    "c-sharp-.net": ".NET",
    "c-sharp-net": ".NET",
    "cpp": "C++",
    "css": "CSS",
    "css3": "CSS",
    "cyber-security": "Cybersecurity",
    "ci-cd": "CI/CD",
    "docker": "Docker",
    "docker-compose": "Docker Compose",
    "dotnet": ".NET",
    "dotnet-core": ".NET",
    "net-4": ".NET",
    "net-4-0": ".NET",
    "net-4-8": ".NET",
    "net-5": ".NET",
    "net-6": ".NET",
    "net-7": ".NET",
    "net-8": ".NET",
    "net-core": ".NET",
    "net-api": ".NET",
    "net-ecosystem": ".NET",
    "net-framework": ".NET",
    "net-maui": ".NET MAUI",
    "net-playwright": ".NET",
    "net-zero-framework": ".NET",
    "express-js": "Express",
    "express.js": "Express",
    "expressjs": "Express",
    "fast-api": "FastAPI",
    "firebase": "Firebase",
    "firestore": "Firestore",
    "flutter": "Flutter",
    "gcp": "Google Cloud",
    "gitlab": "GitLab",
    "git-github": "Git/GitHub",
    "golang": "Go",
    "graphql": "GraphQL",
    "html": "HTML",
    "html5": "HTML",
    "javascript": "JavaScript",
    "javascript-es6": "JavaScript",
    "javascript-es6+": "JavaScript",
    "jira": "Jira",
    "js": "JavaScript",
    "k8s": "Kubernetes",
    "mongodb": "MongoDB",
    "ms-office": "Microsoft Office",
    "mui": "MUI",
    "mysql": "MySQL",
    "nest-js": "NestJS",
    "nest.js": "NestJS",
    "nestjs": "NestJS",
    "next": "Next.js",
    "next-js": "Next.js",
    "next.js": "Next.js",
    "nextjs": "Next.js",
    "node": "Node.js",
    "node-js": "Node.js",
    "node.js": "Node.js",
    "nodejs": "Node.js",
    "openapi-swagger": "OpenAPI/Swagger",
    "postgres": "PostgreSQL",
    "postgresql": "PostgreSQL",
    "python": "Python",
    "react-js": "React",
    "react-native": "React Native",
    "react.js": "React",
    "reactjs": "React",
    "prompt-engineer": "Prompt Engineering",
    "reverse-engineer": "Reverse Engineering",
    "redux-toolkit": "Redux Toolkit",
    "rest": "REST APIs",
    "rest-api": "REST APIs",
    "rest-apis": "REST APIs",
    "restful": "REST APIs",
    "restful-api": "REST APIs",
    "restful-apis": "REST APIs",
    "seo": "SEO",
    "sql": "SQL",
    "sql-server": "SQL Server",
    "swagger-openapi": "OpenAPI/Swagger",
    "tailwind": "Tailwind CSS",
    "tailwind-css": "Tailwind CSS",
    "tailwindcss": "Tailwind CSS",
    "ts": "TypeScript",
    "typescript": "TypeScript",
    "ui-ux": "UI/UX",
    "ux-ui": "UI/UX",
    "vb-.net": "VB.NET",
    "vba.net": "VB.NET",
    "vba-net": "VB.NET",
    "vb.net": "VB.NET",
    "microsoft-visual-studio-.net": "Visual Studio",
    "microsoft-visual-studio-net": "Visual Studio",
    "vue-js": "Vue",
    "vue.js": "Vue",
    "vuejs": "Vue",
    "websocket": "WebSocket",
    "websockets": "WebSocket",
    "windows-server-2012": "Windows Server",
    "windows-server-2016": "Windows Server",
    "windows-server-2019": "Windows Server",
    "windows-server-2022": "Windows Server",
    "wordpress": "WordPress",
}

SKILL_PHRASE_ALIASES = (
    (re.compile(r"\basp\.?\s*net\s*core\b", re.IGNORECASE), "ASP.NET Core"),
    (re.compile(r"\basp\.?\s*net\b", re.IGNORECASE), "ASP.NET"),
    (re.compile(r"\b(?:\.net|dotnet|net)\s*(?:core|framework|[45678](?:\.0|\.8)?|\+[58])\b", re.IGNORECASE), ".NET"),
    (re.compile(r"\bangular\s*(?:js|[0-9]+(?:\+)?)\b", re.IGNORECASE), "Angular"),
    (re.compile(r"\breact\s*(?:js|\.js|[0-9]+)\b", re.IGNORECASE), "React"),
    (re.compile(r"\bvue\s*(?:js|\.js|[0-9]+)\b", re.IGNORECASE), "Vue"),
    (re.compile(r"\bnext\s*(?:js|\.js|[0-9]+)\b", re.IGNORECASE), "Next.js"),
    (re.compile(r"\bnode\s*(?:js|\.js)\b", re.IGNORECASE), "Node.js"),
    (re.compile(r"\bexpress\s*(?:js|\.js)\b", re.IGNORECASE), "Express"),
    (re.compile(r"\bhtml\s*5\b", re.IGNORECASE), "HTML"),
    (re.compile(r"\bcss\s*3\b", re.IGNORECASE), "CSS"),
    (re.compile(r"\bphp\s*[578](?:\.\d+)?\+?\b", re.IGNORECASE), "PHP"),
    (re.compile(r"\bjava\s*8\b", re.IGNORECASE), "Java"),
    (re.compile(r"\brestful?\s+apis?\b|\brest\s+apis?\b|\brestapis\b", re.IGNORECASE), "REST APIs"),
    (re.compile(r"\bms\s*office\s*20\d{2}\b|\bmicrosoft office\b|\bms office\b", re.IGNORECASE), "Microsoft Office"),
    (re.compile(r"\bwindows server\s*(?:20\d{2}(?:[/, -]+20\d{2})*)?\b", re.IGNORECASE), "Windows Server"),
    (re.compile(r"\bvisual studio\s*20\d{2}\b", re.IGNORECASE), "Visual Studio"),
)

SKILL_DROP_EXACT = {
    "0934-650-619",
    "10",
    "achievements",
    "achievements-tasks",
    "abd-alrahman-karaja-6850bbb6",
    "accounting-manager",
    "and",
    "and-deliverables",
    "and-monitoring",
    "and-security",
    "back-end",
    "backend",
    "backend-developer",
    "computer-skills",
    "damascus",
    "damascus-dwaila",
    "damascus-governorate",
    "damascus-software-developer",
    "damascus-syria",
    "damascus-university-expected-nov-2025",
    "data-analyst",
    "front-end",
    "frontend",
    "full-stack",
    "government-employee",
    "https",
    "in",
    "linkedin",
    "office-manager",
    "programming-languages",
    "projects",
    "responsibilities",
    "skills",
    "soc-analyst",
    "soft-skills",
    "souccar-for-electronic-industries-sei",
    "sql-developer",
    "st-company",
    "syria",
    "technical-skills",
    "technologies",
    "tools",
    "web-developer",
    "which-are-currently-running",
    "with",
    "work",
    "www-linkedin-com",
    "designed",
}

SKILL_ROLE_ONLY_RE = re.compile(
    r"^(?:(?:junior|senior|sr|lead|mid(?:dle)?|full[-\s]?time|freelance)\s+)?"
    r"(?:(?:flutter|laravel|web|front[-\s]?end|back[-\s]?end|full[-\s]?stack|software|sql|soc|data|accounting|office|mobile|android|ios|php|react|node(?:\.js)?|\.net|asp\.net|ai)\s+)?"
    r"(?:developer|engineer|analyst|manager|consultant|designer|administrator)"
    r"(?:\s*\([^)]*\))?$",
    re.IGNORECASE,
)

SKILL_DATE_RANGE_RE = re.compile(
    r"^\s*(?:[A-Za-z]+\s+)?(?:19|20)\d{2}\s*[-–]\s*(?:present|current|(?:[A-Za-z]+\s+)?(?:19|20)\d{2})\s*$",
    re.IGNORECASE,
)
SKILL_CONTACT_RE = re.compile(r"@|https?://|www\.|(?:linkedin|github|gitlab)\.com/", re.IGNORECASE)

ROLE_PATTERNS = {
    "full-stack": ["full stack", "full-stack"],
    "mobile": ["mobile", "flutter", "android", "ios", "react native", "swift", "kotlin"],
    "frontend": ["frontend", "front-end", "front end", "react", "next.js", "angular", "vue", "html", "css", "ui/ux", "webflow"],
    "backend": ["backend", "back-end", "back end", "api", "microservice", "node.js", "nestjs", ".net", "asp.net", "django", "flask", "fastapi", "laravel"],
    "devops": ["devops", "sre", "terraform", "kubernetes", "docker", "ci/cd", "cloud infrastructure"],
    "data": ["data engineer", "analytics", "etl", "pandas", "numpy", "bi", "data analysis"],
    "ml": ["machine learning", "ml", "ai engineer", "llm", "tensorflow", "pytorch", "scikit-learn"],
    "qa": ["qa", "quality assurance", "automation testing", "test automation", "selenium"],
    "security": ["security", "cybersecurity", "siem", "soc", "threat detection", "penetration testing", "vulnerability"],
}

ROLE_TAG_ALIASES = {
    "fullstack": "full-stack",
    "full-stack": "full-stack",
    "frontend": "frontend",
    "front-end": "frontend",
    "backend": "backend",
    "back-end": "backend",
    "mobile": "mobile",
    "devops": "devops",
    "sre": "devops",
    "data": "data",
    "ml": "ml",
    "ai": "ml",
    "qa": "qa",
    "security": "security",
    "cybersecurity": "security",
}

SENIORITY_ALIASES = {
    "entry-level": "junior",
    "entry-levels": "junior",
    "intern": "junior",
    "junior": "junior",
    "jr": "junior",
    "junior-level": "junior",
    "mid": "mid",
    "middle": "mid",
    "mid-level": "mid",
    "midlevel": "mid",
    "mid-senior": "senior",
    "senior": "senior",
    "sr": "senior",
    "sr.": "senior",
    "lead": "staff-plus",
    "principal": "staff-plus",
    "staff": "staff-plus",
    "architect": "staff-plus",
    "head": "staff-plus",
    "staff-plus": "staff-plus",
    "unclassified": "unclassified",
    "unknown": "unclassified",
}

ROLE_HINT_RE = re.compile(
    r"\b(front[\s-]?end|back[\s-]?end|full[\s-]?stack|mobile|flutter|android|ios|developer|engineer|architect|designer|manager|analyst|specialist|consultant|administrator|seo|security|devops|sre|qa)\b",
    re.IGNORECASE,
)
LOCATION_PATTERN = re.compile(r"^[A-Za-z .'-]+,\s*[A-Za-z .'-]+$")
CONTACT_PATTERN = re.compile(r"@|https?://|linkedin|github|portfolio|\+\d")
DATE_FRAGMENT_RE = re.compile(r"\b(?:19|20)\d{2}\b")
YEARS_PATTERN = re.compile(
    r"\b(?P<count>\d+|one|two|three|four|five|six|seven|eight|nine|ten)\+?\s+years?\b",
    re.IGNORECASE,
)
TITLE_VERB_RE = re.compile(r"\b(collaborated|implemented|developed|built|worked|improved|led|designed|optimized|conducted)\b", re.IGNORECASE)
DATE_RANGE_PATTERN = re.compile(
    r"(?P<start>(?:\d{1,2}/)?\d{4}|present|current)\s*[-–]\s*(?P<end>(?:\d{1,2}/)?\d{4}|present|current)",
    re.IGNORECASE,
)
SENIOR_SIGNAL_RE = re.compile(r"\b(senior|principal|staff|lead|architect|head of)\b", re.IGNORECASE)
JUNIOR_SIGNAL_RE = re.compile(r"\b(junior|intern|entry(?:\s|-)?level)\b", re.IGNORECASE)
MAX_REASONABLE_YEARS_EXPERIENCE = 80.0
GENERIC_EXPERIENCE_TITLE_RE = re.compile(
    r"\b(project leadership|client engagement|key achievements?|responsibilities|achievements?)\b",
    re.IGNORECASE,
)
WORK_EXPERIENCE_TITLE_RE = re.compile(
    r"\b(developer|engineer|specialist|manager|analyst|designer|consultant|administrator|architect|seo|security|devops|sre|qa|growth[\s-]?hacker)\b",
    re.IGNORECASE,
)
ACADEMIC_HINTS = (
    "information technology",
    "computer engineering",
    "software engineering",
    "artificial intelligence",
    "informatics",
    "bachelor",
    "degree",
    "student",
)
LOCATION_SEGMENT_PATTERN = re.compile(r"^[A-Za-z .'-]+$")
LOCATION_WORD_RE = re.compile(r"[A-Za-z]+(?:'[A-Za-z]+)?")
GEO_ACRONYMS = {"uae", "uk", "usa", "ksa"}
LOCATION_CONNECTOR_TOKENS = {"and", "of", "the", "al", "de", "la", "st", "saint"}
COUNTRY_ALIASES = {
    "bahrain": "Bahrain",
    "canada": "Canada",
    "egypt": "Egypt",
    "france": "France",
    "germany": "Germany",
    "iraq": "Iraq",
    "jordan": "Jordan",
    "ksa": "Saudi Arabia",
    "kuwait": "Kuwait",
    "lebanon": "Lebanon",
    "oman": "Oman",
    "qatar": "Qatar",
    "saudi-arabia": "Saudi Arabia",
    "syria": "Syria",
    "syrian-arab-republic": "Syria",
    "turkey": "Turkey",
    "uae": "United Arab Emirates",
    "uk": "United Kingdom",
    "united-arab-emirates": "United Arab Emirates",
    "united-kingdom": "United Kingdom",
    "united-states": "United States",
    "usa": "United States",
}
CITY_ALIASES = {
    "aleppo": "Aleppo",
    "cairo": "Cairo",
    "damascus": "Damascus",
    "damscus": "Damascus",
    "montreal": "Montreal",
}
IMPLICIT_COUNTRY_BY_CITY = {
    "aleppo": "Syria",
    "cairo": "Egypt",
    "damascus": "Syria",
    "montreal": "Canada",
}
BLOCKED_LOCATION_TOKENS = {
    "agency",
    "adobe",
    "ai",
    "api",
    "apis",
    "app",
    "application",
    "applications",
    "amos",
    "aws",
    "backend",
    "bank",
    "company",
    "consultant",
    "crm",
    "cms",
    "css",
    "dashboard",
    "data",
    "department",
    "developer",
    "devops",
    "docker",
    "engineer",
    "erp",
    "figma",
    "first",
    "foundation",
    "frontend",
    "full",
    "github",
    "groups",
    "growth",
    "hacker",
    "html",
    "hybrid",
    "javascript",
    "kubernetes",
    "lab",
    "labs",
    "laravel",
    "lead",
    "linkedin",
    "manager",
    "marketing",
    "nationality",
    "node",
    "onsite",
    "on",
    "php",
    "platform",
    "pressure",
    "project",
    "projects",
    "evacuation",
    "python",
    "qa",
    "aid",
    "react",
    "remote",
    "sales",
    "seo",
    "software",
    "spss",
    "specialist",
    "sql",
    "stack",
    "suite",
    "sketch",
    "system",
    "systems",
    "team",
    "technical",
    "technology",
    "technologies",
    "tools",
    "university",
    "ux",
    "ui",
    "web",
    "wordpress",
    "work",
}
BLOCKED_LOCATION_PHRASES = {
    "full-time",
    "part-time",
    "on-site",
    "work from home",
}
