from __future__ import annotations

import re


JOB_FAMILY_TAXONOMY_VERSION = "production-corpus-v1"
JOB_FAMILY_LABELS = (
    "Full-Stack Engineering",
    "Backend Engineering",
    "Frontend Engineering",
    "Mobile Engineering",
    "AI & Machine Learning",
    "Data & Analytics",
    "Cloud, DevOps & SRE",
    "Cybersecurity",
    "QA & Test Automation",
    "Product & Design",
    "Software Engineering",
    "Unclassified",
)
CONTACT_PATTERN = re.compile(r"@|https?://|linkedin|github|portfolio|\+\d")
DATE_FRAGMENT_RE = re.compile(r"\b(?:19|20)\d{2}\b")
LOCATION_SEGMENT_PATTERN = re.compile(r"^[A-Za-z .'-]+$")
LOCATION_WORD_RE = re.compile(r"[A-Za-z]+(?:'[A-Za-z]+)?")
GEO_ACRONYMS = {"uae", "uk", "usa", "ksa"}
LOCATION_CONNECTOR_TOKENS = {"and", "of", "the", "al", "de", "la", "st", "saint"}
COUNTRY_ALIASES = {
    "bahrain": "Bahrain",
    "canada": "Canada",
    "egypt": "Egypt",
    "france": "France",
    "germany": "Germany",
    "iraq": "Iraq",
    "jordan": "Jordan",
    "ksa": "Saudi Arabia",
    "kuwait": "Kuwait",
    "lebanon": "Lebanon",
    "oman": "Oman",
    "qatar": "Qatar",
    "saudi-arabia": "Saudi Arabia",
    "syria": "Syria",
    "syrian-arab-republic": "Syria",
    "turkey": "Turkey",
    "uae": "United Arab Emirates",
    "uk": "United Kingdom",
    "united-arab-emirates": "United Arab Emirates",
    "united-kingdom": "United Kingdom",
    "united-states": "United States",
    "usa": "United States",
}
CITY_ALIASES = {
    "aleppo": "Aleppo",
    "cairo": "Cairo",
    "damascus": "Damascus",
    "damscus": "Damascus",
    "montreal": "Montreal",
}
BLOCKED_LOCATION_TOKENS = {
    "agency",
    "adobe",
    "ai",
    "api",
    "apis",
    "app",
    "application",
    "applications",
    "amos",
    "aws",
    "backend",
    "bank",
    "company",
    "consultant",
    "crm",
    "cms",
    "css",
    "dashboard",
    "data",
    "department",
    "developer",
    "devops",
    "docker",
    "engineer",
    "erp",
    "figma",
    "first",
    "foundation",
    "frontend",
    "full",
    "github",
    "groups",
    "growth",
    "hacker",
    "html",
    "hybrid",
    "javascript",
    "kubernetes",
    "lab",
    "labs",
    "laravel",
    "lead",
    "linkedin",
    "manager",
    "marketing",
    "nationality",
    "node",
    "onsite",
    "on",
    "php",
    "platform",
    "pressure",
    "project",
    "projects",
    "evacuation",
    "python",
    "qa",
    "aid",
    "react",
    "remote",
    "sales",
    "seo",
    "software",
    "spss",
    "specialist",
    "sql",
    "stack",
    "suite",
    "sketch",
    "system",
    "systems",
    "team",
    "technical",
    "technology",
    "technologies",
    "tools",
    "university",
    "ux",
    "ui",
    "web",
    "wordpress",
    "work",
}
BLOCKED_LOCATION_PHRASES = {
    "full-time",
    "part-time",
    "on-site",
    "work from home",
}
