from __future__ import annotations

from ..normalization_constants import (
    ACADEMIC_HINTS,
    CONTACT_PATTERN,
    DATE_FRAGMENT_RE,
    GENERIC_EXPERIENCE_TITLE_RE,
    LOCATION_PATTERN,
    ROLE_HINT_RE,
    TITLE_VERB_RE,
    WORK_EXPERIENCE_TITLE_RE,
)
from ..schema import ExperienceEntry
from ..utils import compact_whitespace


def is_title_like(value: str, *, allow_long: bool = False) -> bool:
    text = compact_whitespace(value)
    if not text:
        return False
    if "years of experience" in text.lower():
        return False
    if TITLE_VERB_RE.search(text):
        return False
    if CONTACT_PATTERN.search(text):
        return False
    if LOCATION_PATTERN.match(text):
        return False
    if text.lower().startswith("generated by "):
        return False
    if DATE_FRAGMENT_RE.search(text):
        return False
    if any(term in text.lower() for term in ACADEMIC_HINTS) and not ROLE_HINT_RE.search(text):
        return False
    max_words = 14 if allow_long else 10
    if len(text.split()) > max_words and not ROLE_HINT_RE.search(text):
        return False
    return bool(ROLE_HINT_RE.search(text))


def is_countable_experience_entry(entry: ExperienceEntry) -> bool:
    title = compact_whitespace(entry.title)
    if not title:
        return False
    if GENERIC_EXPERIENCE_TITLE_RE.search(title):
        return False
    if WORK_EXPERIENCE_TITLE_RE.search(title):
        return True
    return is_title_like(title, allow_long=True)


def count_work_like_experience_entries(entries: list[ExperienceEntry]) -> int:
    return sum(1 for entry in entries if is_countable_experience_entry(entry))
