// frontend/src/features/search/utils/countryFlags.ts
const FALLBACK_FLAG = "https://hatscripts.github.io/circle-flags/flags/xx.svg";

// Comprehensive mapping of ALL countries, territories, aliases, and abbreviations to circle-flag codes
export const COUNTRY_MAP: Record<string, { name: string; code: string }> = {
  "any place": {name: "Any Place", code: ""},
  "any place.": {name: "Any Place", code: ""},
  "afghanistan": {name: "Afghanistan", code: "af"},
  "aland islands": {name: "Åland Islands", code: "ax"},
  "albania": {name: "Albania", code: "al"},
  "algeria": {name: "Algeria", code: "dz"},
  "american samoa": {name: "American Samoa", code: "as"},
  "andorra": {name: "Andorra", code: "ad"},
  "angola": {name: "Angola", code: "ao"},
  "anguilla": {name: "Anguilla", code: "ai"},
  "antarctica": {name: "Antarctica", code: "aq"},
  "antigua and barbuda": {name: "Antigua and Barbuda", code: "ag"},
  "argentina": {name: "Argentina", code: "ar"},
  "armenia": {name: "Armenia", code: "am"},
  "aruba": {name: "Aruba", code: "aw"},
  "australia": {name: "Australia", code: "au"},
  "austria": {name: "Austria", code: "at"},
  "azerbaijan": {name: "Azerbaijan", code: "az"},
  "bahamas": {name: "Bahamas", code: "bs"},
  "bahrain": {name: "Bahrain", code: "bh"},
  "bangladesh": {name: "Bangladesh", code: "bd"},
  "barbados": {name: "Barbados", code: "bb"},
  "belarus": {name: "Belarus", code: "by"},
  "belgium": {name: "Belgium", code: "be"},
  "belize": {name: "Belize", code: "bz"},
  "benin": {name: "Benin", code: "bj"},
  "bermuda": {name: "Bermuda", code: "bm"},
  "bhutan": {name: "Bhutan", code: "bt"},
  "bolivia": {name: "Bolivia", code: "bo"},
  "bonaire": {name: "Bonaire", code: "bq"},
  "bosnia": {name: "Bosnia and Herzegovina", code: "ba"},
  "bosnia and herzegovina": {name: "Bosnia and Herzegovina", code: "ba"},
  "botswana": {name: "Botswana", code: "bw"},
  "bouvet island": {name: "Bouvet Island", code: "bv"},
  "brazil": {name: "Brazil", code: "br"},
  "british indian ocean territory": {name: "British Indian Ocean Territory", code: "io"},
  "brunei": {name: "Brunei", code: "bn"},
  "brunei darussalam": {name: "Brunei", code: "bn"},
  "bulgaria": {name: "Bulgaria", code: "bg"},
  "burkina faso": {name: "Burkina Faso", code: "bf"},
  "burundi": {name: "Burundi", code: "bi"},
  "cabo verde": {name: "Cabo Verde", code: "cv"},
  "cape verde": {name: "Cabo Verde", code: "cv"},
  "cambodia": {name: "Cambodia", code: "kh"},
  "cameroon": {name: "Cameroon", code: "cm"},
  "canada": {name: "Canada", code: "ca"},
  "ca": {name: "Canada", code: "ca"},
  "cayman islands": {name: "Cayman Islands", code: "ky"},
  "central african republic": {name: "Central African Republic", code: "cf"},
  "chad": {name: "Chad", code: "td"},
  "chile": {name: "Chile", code: "cl"},
  "china": {name: "China", code: "cn"},
  "christmas island": {name: "Christmas Island", code: "cx"},
  "cocos islands": {name: "Cocos (Keeling) Islands", code: "cc"},
  "cocos (keeling) islands": {name: "Cocos (Keeling) Islands", code: "cc"},
  "colombia": {name: "Colombia", code: "co"},
  "comoros": {name: "Comoros", code: "km"},
  "congo": {name: "Congo (Republic)", code: "cg"},
  "congo (dem. rep.)": {name: "Congo (DRC)", code: "cd"},
  "congo (democratic republic)": {name: "Congo (DRC)", code: "cd"},
  "congo (drc)": {name: "Congo (DRC)", code: "cd"},
  "congo (republic)": {name: "Congo (Republic)", code: "cg"},
  "cook islands": {name: "Cook Islands", code: "ck"},
  "costa rica": {name: "Costa Rica", code: "cr"},
  "cote d'ivoire": {name: "Côte d'Ivoire", code: "ci"},
  "ivory coast": {name: "Côte d'Ivoire", code: "ci"},
  "croatia": {name: "Croatia", code: "hr"},
  "cuba": {name: "Cuba", code: "cu"},
  "curacao": {name: "Curaçao", code: "cw"},
  "cyprus": {name: "Cyprus", code: "cy"},
  "czechia": {name: "Czechia", code: "cz"},
  "czech republic": {name: "Czechia", code: "cz"},
  "denmark": {name: "Denmark", code: "dk"},
  "djibouti": {name: "Djibouti", code: "dj"},
  "dominica": {name: "Dominica", code: "dm"},
  "dominican republic": {name: "Dominican Republic", code: "do"},
  "ecuador": {name: "Ecuador", code: "ec"},
  "egypt": {name: "Egypt", code: "eg"},
  "el salvador": {name: "El Salvador", code: "sv"},
  "equatorial guinea": {name: "Equatorial Guinea", code: "gq"},
  "eritrea": {name: "Eritrea", code: "er"},
  "estonia": {name: "Estonia", code: "ee"},
  "eswatini": {name: "Eswatini", code: "sz"},
  "swaziland": {name: "Eswatini", code: "sz"},
  "ethiopia": {name: "Ethiopia", code: "et"},
  "falkland islands": {name: "Falkland Islands", code: "fk"},
  "faroe islands": {name: "Faroe Islands", code: "fo"},
  "fiji": {name: "Fiji", code: "fj"},
  "finland": {name: "Finland", code: "fi"},
  "france": {name: "France", code: "fr"},
  "french guiana": {name: "French Guiana", code: "gf"},
  "french polynesia": {name: "French Polynesia", code: "pf"},
  "french southern territories": {name: "French Southern Territories", code: "tf"},
  "gabon": {name: "Gabon", code: "ga"},
  "gambia": {name: "Gambia", code: "gm"},
  "georgia": {name: "Georgia", code: "ge"},
  "germany": {name: "Germany", code: "de"},
  "ghana": {name: "Ghana", code: "gh"},
  "gibraltar": {name: "Gibraltar", code: "gi"},
  "greece": {name: "Greece", code: "gr"},
  "greenland": {name: "Greenland", code: "gl"},
  "grenada": {name: "Grenada", code: "gd"},
  "guadeloupe": {name: "Guadeloupe", code: "gp"},
  "guam": {name: "Guam", code: "gu"},
  "guatemala": {name: "Guatemala", code: "gt"},
  "guernsey": {name: "Guernsey", code: "gg"},
  "guinea": {name: "Guinea", code: "gn"},
  "guinea-bissau": {name: "Guinea-Bissau", code: "gw"},
  "guyana": {name: "Guyana", code: "gy"},
  "haiti": {name: "Haiti", code: "ht"},
  "heard island and mcdonald islands": {name: "Heard Island and McDonald Islands", code: "hm"},
  "holy see": {name: "Holy See", code: "va"},
  "vatican city": {name: "Holy See", code: "va"},
  "honduras": {name: "Honduras", code: "hn"},
  "hong kong": {name: "Hong Kong", code: "hk"},
  "hk": {name: "Hong Kong", code: "hk"},
  "hungary": {name: "Hungary", code: "hu"},
  "iceland": {name: "Iceland", code: "is"},
  "india": {name: "India", code: "in"},
  "indonesia": {name: "Indonesia", code: "id"},
  "iran": {name: "Iran", code: "ir"},
  "iraq": {name: "Iraq", code: "iq"},
  "ireland": {name: "Ireland", code: "ie"},
  "isle of man": {name: "Isle of Man", code: "im"},
  "italy": {name: "Italy", code: "it"},
  "jamaica": {name: "Jamaica", code: "jm"},
  "japan": {name: "Japan", code: "jp"},
  "jersey": {name: "Jersey", code: "je"},
  "jordan": {name: "Jordan", code: "jo"},
  "kazakhstan": {name: "Kazakhstan", code: "kz"},
  "kenya": {name: "Kenya", code: "ke"},
  "kiribati": {name: "Kiribati", code: "ki"},
  "north korea": {name: "North Korea", code: "kp"},
  "korea (democratic people's republic)": {name: "North Korea", code: "kp"},
  "south korea": {name: "South Korea", code: "kr"},
  "korea (republic)": {name: "South Korea", code: "kr"},
  "kuwait": {name: "Kuwait", code: "kw"},
  "kyrgyzstan": {name: "Kyrgyzstan", code: "kg"},
  "laos": {name: "Laos", code: "la"},
  "lao people's democratic republic": {name: "Laos", code: "la"},
  "latvia": {name: "Latvia", code: "lv"},
  "lebanon": {name: "Lebanon", code: "lb"},
  "lesotho": {name: "Lesotho", code: "ls"},
  "liberia": {name: "Liberia", code: "lr"},
  "libya": {name: "Libya", code: "ly"},
  "liechtenstein": {name: "Liechtenstein", code: "li"},
  "lithuania": {name: "Lithuania", code: "lt"},
  "luxembourg": {name: "Luxembourg", code: "lu"},
  "macao": {name: "Macao", code: "mo"},
  "macau": {name: "Macao", code: "mo"},
  "madagascar": {name: "Madagascar", code: "mg"},
  "malawi": {name: "Malawi", code: "mw"},
  "malaysia": {name: "Malaysia", code: "my"},
  "maldives": {name: "Maldives", code: "mv"},
  "mali": {name: "Mali", code: "ml"},
  "malta": {name: "Malta", code: "mt"},
  "marshall islands": {name: "Marshall Islands", code: "mh"},
  "martinique": {name: "Martinique", code: "mq"},
  "mauritania": {name: "Mauritania", code: "mr"},
  "mauritius": {name: "Mauritius", code: "mu"},
  "mayotte": {name: "Mayotte", code: "yt"},
  "mexico": {name: "Mexico", code: "mx"},
  "micronesia": {name: "Micronesia", code: "fm"},
  "moldova": {name: "Moldova", code: "md"},
  "monaco": {name: "Monaco", code: "mc"},
  "mongolia": {name: "Mongolia", code: "mn"},
  "montenegro": {name: "Montenegro", code: "me"},
  "montserrat": {name: "Montserrat", code: "ms"},
  "morocco": {name: "Morocco", code: "ma"},
  "mozambique": {name: "Mozambique", code: "mz"},
  "myanmar": {name: "Myanmar", code: "mm"},
  "burma": {name: "Myanmar", code: "mm"},
  "namibia": {name: "Namibia", code: "na"},
  "nauru": {name: "Nauru", code: "nr"},
  "nepal": {name: "Nepal", code: "np"},
  "netherlands": {name: "Netherlands", code: "nl"},
  "new caledonia": {name: "New Caledonia", code: "nc"},
  "new zealand": {name: "New Zealand", code: "nz"},
  "nicaragua": {name: "Nicaragua", code: "ni"},
  "niger": {name: "Niger", code: "ne"},
  "nigeria": {name: "Nigeria", code: "ng"},
  "niue": {name: "Niue", code: "nu"},
  "norfolk island": {name: "Norfolk Island", code: "nf"},
  "north macedonia": {name: "North Macedonia", code: "mk"},
  "macedonia": {name: "North Macedonia", code: "mk"},
  "northern mariana islands": {name: "Northern Mariana Islands", code: "mp"},
  "norway": {name: "Norway", code: "no"},
  "oman": {name: "Oman", code: "om"},
  "pakistan": {name: "Pakistan", code: "pk"},
  "palau": {name: "Palau", code: "pw"},
  "palestine": {name: "Palestine", code: "ps"},
  "panama": {name: "Panama", code: "pa"},
  "papua new guinea": {name: "Papua New Guinea", code: "pg"},
  "paraguay": {name: "Paraguay", code: "py"},
  "peru": {name: "Peru", code: "pe"},
  "philippines": {name: "Philippines", code: "ph"},
  "pitcairn": {name: "Pitcairn", code: "pn"},
  "poland": {name: "Poland", code: "pl"},
  "portugal": {name: "Portugal", code: "pt"},
  "puerto rico": {name: "Puerto Rico", code: "pr"},
  "qatar": {name: "Qatar", code: "qa"},
  "reunion": {name: "Réunion", code: "re"},
  "romania": {name: "Romania", code: "ro"},
  "russia": {name: "Russia", code: "ru"},
  "russian federation": {name: "Russia", code: "ru"},
  "rwanda": {name: "Rwanda", code: "rw"},
  "saint barthelemy": {name: "Saint Barthélemy", code: "bl"},
  "saint helena": {name: "Saint Helena", code: "sh"},
  "saint kitts and nevis": {name: "Saint Kitts and Nevis", code: "kn"},
  "saint lucia": {name: "Saint Lucia", code: "lc"},
  "saint martin": {name: "Saint Martin", code: "mf"},
  "saint pierre and miquelon": {name: "Saint Pierre and Miquelon", code: "pm"},
  "saint vincent and the grenadines": {name: "Saint Vincent and the Grenadines", code: "vc"},
  "samoa": {name: "Samoa", code: "ws"},
  "san marino": {name: "San Marino", code: "sm"},
  "sao tome and principe": {name: "São Tomé and Príncipe", code: "st"},
  "saudi arabia": {name: "Saudi Arabia", code: "sa"},
  "senegal": {name: "Senegal", code: "sn"},
  "serbia": {name: "Serbia", code: "rs"},
  "seychelles": {name: "Seychelles", code: "sc"},
  "sierra leone": {name: "Sierra Leone", code: "sl"},
  "singapore": {name: "Singapore", code: "sg"},
  "sint maarten": {name: "Sint Maarten", code: "sx"},
  "slovakia": {name: "Slovakia", code: "sk"},
  "slovenia": {name: "Slovenia", code: "si"},
  "solomon islands": {name: "Solomon Islands", code: "sb"},
  "somalia": {name: "Somalia", code: "so"},
  "south africa": {name: "South Africa", code: "za"},
  "south georgia": {name: "South Georgia", code: "gs"},
  "south sudan": {name: "South Sudan", code: "ss"},
  "spain": {name: "Spain", code: "es"},
  "sri lanka": {name: "Sri Lanka", code: "lk"},
  "sudan": {name: "Sudan", code: "sd"},
  "suriname": {name: "Suriname", code: "sr"},
  "svalbard": {name: "Svalbard", code: "sj"},
  "sweden": {name: "Sweden", code: "se"},
  "switzerland": {name: "Switzerland", code: "ch"},
  "syria": {name: "Syrian Arab Republic", code: "sy"},
  "syrian arab republic": {name: "Syrian Arab Republic", code: "sy"},
  "taiwan": {name: "Taiwan", code: "tw"},
  "tajikistan": {name: "Tajikistan", code: "tj"},
  "tanzania": {name: "Tanzania", code: "tz"},
  "thailand": {name: "Thailand", code: "th"},
  "timor-leste": {name: "Timor-Leste", code: "tl"},
  "togo": {name: "Togo", code: "tg"},
  "tokelau": {name: "Tokelau", code: "tk"},
  "tonga": {name: "Tonga", code: "to"},
  "trinidad and tobago": {name: "Trinidad and Tobago", code: "tt"},
  "tunisia": {name: "Tunisia", code: "tn"},
  "turkey": {name: "Turkey", code: "tr"},
  "turkmenistan": {name: "Turkmenistan", code: "tm"},
  "turks and caicos islands": {name: "Turks and Caicos Islands", code: "tc"},
  "tuvalu": {name: "Tuvalu", code: "tv"},
  "uganda": {name: "Uganda", code: "ug"},
  "ukraine": {name: "Ukraine", code: "ua"},
  "united arab emirates": {name: "United Arab Emirates", code: "ae"},
  "uae": {name: "United Arab Emirates", code: "ae"},
  "united kingdom": {name: "United Kingdom", code: "gb"},
  "uk": {name: "United Kingdom", code: "gb"},
  "united states": {name: "United States", code: "us"},
  "usa": {name: "United States", code: "us"},
  "us": {name: "United States", code: "us"},
  "uruguay": {name: "Uruguay", code: "uy"},
  "uzbekistan": {name: "Uzbekistan", code: "uz"},
  "vanuatu": {name: "Vanuatu", code: "vu"},
  "venezuela": {name: "Venezuela", code: "ve"},
  "vietnam": {name: "Vietnam", code: "vn"},
  "british virgin islands": {name: "British Virgin Islands", code: "vg"},
  "virgin islands (british)": {name: "British Virgin Islands", code: "vg"},
  "us virgin islands": {name: "US Virgin Islands", code: "vi"},
  "virgin islands (us)": {name: "US Virgin Islands", code: "vi"},
  "wallis and futuna": {name: "Wallis and Futuna", code: "wf"},
  "western sahara": {name: "Western Sahara", code: "eh"},
  "yemen": {name: "Yemen", code: "ye"},
  "zambia": {name: "Zambia", code: "zm"},
  "zimbabwe": {name: "Zimbabwe", code: "zw"}
};

export function getCleanCountry(locationString: string): { name: string; flagUrl: string | null } {
  const parts = locationString.split(",");
  const rawCountry = parts[parts.length - 1].trim().toLowerCase();

  const match = COUNTRY_MAP[rawCountry];
  if (match) {
    const nameValue = match.name === "Any Place" ? "Any Place" : match.name;

    // Explicit return to always bypass/hide flag illustration for "Any Place"
    if (nameValue === "Any Place") {
      return {
        name: "Any Place",
        flagUrl: null,
      };
    }

    const pathPrefix = match.code.includes("other") ? "" : "flags/";
    return {
      name: nameValue,
      flagUrl: `https://hatscripts.github.io/circle-flags/${pathPrefix}${match.code}.svg`,
    };
  }

  // Fallback to title-cased name and standard fallback circular flag SVG
  const cleanFallbackName = locationString.replace(/(^\w|\s\w)/g, (match) => match.toUpperCase());
  return {
    name: cleanFallbackName,
    flagUrl: FALLBACK_FLAG,
  };
}
